language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '8'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jobs:
  stages:
    - test
    - release
  include:
    - stage: test
      script: npm run test-and-codecov
    - stage: release
      if: branch = master
      script: npm run build-and-release