language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '8'
before_script:
  - npm prune
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
