language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '8'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm test
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
